FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
RUN npm config set registry https://registry.npmmirror.com/
RUN npm config set strict-ssl false
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
